Added unicorn config

diff --git a/unicorn/unicorn.init.d.erb b/unicorn/unicorn.init.d.erb
--- a/unicorn/unicorn.init.d.erb
+++ b/unicorn/unicorn.init.d.erb
@@ -1,89 +1,82 @@
 #! /bin/sh
-# <%= generated_by_babushka %>
 
-# Taken from Unicorn source version 1.1.2
+# File: /etc/init.d/unicorn
 
-set -e
-# Example init script, this can be used with nginx, too,
-# since nginx and unicorn accept the same signals
+### BEGIN INIT INFO
+# Provides:          unicorn
+# Required-Start:    $local_fs $remote_fs $network $syslog
+# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts the unicorn web server
+# Description:       starts unicorn
+### END INIT INFO
 
-# Feel free to change any of the following variables for your app:
-TIMEOUT=60
-APP_ROOT=<%= var :absolute_rails_root %>
-PID=<%= var :app_pid_dir %>/unicorn.pid
-ENV_OPTS="RUBY_HEAP_MIN_SLOTS=1250000 RUBY_HEAP_SLOTS_INCREMENT=250000 RUBY_HEAP_SLOTS_GROWTH_FACTOR=1 RUBY_GC_MALLOC_LIMIT=60000000 RUBY_HEAP_FREE_MIN=100000"
-CMD="<%= var :bin_path %>/unicorn_rails -D -E <%= var :rails_env %> -c <%= var :unicorn_config_within_app %>"
-action="$1"
+RAILS_ENV=production
+RAILS_ROOT=/www/lexim/current
+RAILS_SHARED=/www/lexim/shared
+
 set -u
-
-old_pid="$PID.oldbin"
-
-cd $APP_ROOT || exit 1
+set -e
 
 sig () {
-    test -s "$PID" && kill -$1 `cat $PID`
+  test -s "$PID" && kill -$1 `cat "$PID"`
 }
 
 oldsig () {
-    test -s $old_pid && kill -$1 `cat $old_pid`
+  test -s "$OLD_PID" && kill -$1 `cat "$OLD_PID"`
 }
 
-workersig () {
-    workerpid="/var/run/marketplace/unicorn_$2.pid"
+cmd () {
 
-    test -s "$workerpid" && kill -$1 `cat $workerpid`
-}
-
-case $action in
-start)
+case $1 in
+  start)
     sig 0 && echo >&2 "Already running" && exit 0
-    export $ENV_OPTS
+    echo "Starting"
     $CMD
-;;
-stop)
-    sig QUIT && exit 0
-echo >&2 "Not running"
-;;
-force-stop)
-    sig TERM && exit 0
-echo >&2 "Not running"
-;;
-restart|reload)
-    sig HUP && echo reloaded OK && exit 0
+  ;;
+  stop)
+   sig QUIT && echo "Stopping" && exit 0
+   echo >&2 "Not running"
+  ;;
+  force-stop)
+    sig TERM && echo "Forcing a stop" && exit 0
+    echo >&2 "Not running"
+  ;;
+  restart|reload)
+    sig HUP && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
     echo >&2 "Couldn't reload, starting '$CMD' instead"
-    export $ENV_OPTS
     $CMD
-;;
-upgrade)
-    if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-    then
-        n=$TIMEOUT
-        while test -s $old_pid && test $n -ge 0
-        do
-            printf '.' && sleep 1 && n=$(( $n - 1 ))
-        done
-        echo
-
-        if test $n -lt 0 && test -s $old_pid
-        then
-            echo >&2 "$old_pid still exists after $TIMEOUT seconds"
-            exit 1
-        fi
-        exit 0
-    fi
+  ;;
+  upgrade)
+    sig USR2 && echo Upgraded && exit 0
     echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-    export $ENV_OPTS
     $CMD
-;;
-kill_worker)
-    workersig QUIT $2 && exit 0
-    echo >&2 "Worker not running"
-;;
-reopen-logs)
-    sig USR1
-;;
-*)
-    echo >&2 "Usage: $0 <start|stop|restart|upgrade|force-stop|reopen-logs>"
+  ;;
+  rotate)
+    sig USR1 && echo rotated logs OK && exit 0
+    echo >&2 "Couldn't rotate logs" && exit 1
+  ;;
+  *)
+    echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
     exit 1
-;;
-esac
+  ;;
+  esac
+}
+
+setup () {
+  echo -n "$RAILS_ROOT: "
+  cd $RAILS_ROOT || exit 1
+  export PID=$RAILS_SHARED/pids/unicorn.pid
+  export OLD_PID="$PID.oldbin"
+
+  CMD="$RAILS_ROOT/bin/unicorn_rails --config-file config/unicorn.rb --env production --daemonize"
+}
+
+start_stop () {
+  setup
+  cmd $1
+}
+
+ARGS="$1"
+start_stop $ARGS
